version: "3.4"

services:
  rasa-core-sriram-tamil:
    image: "tatisudheer/chatbot"
    volumes:
        - ./models:/app/models
        - ./constants:/app/constants
    ports:
        - "8830:8830"
    network_mode: "host"
    command:
        - -m
        - rasa
        - run
        - --enable-api
        - -m
        - models/emi_english/emi_english_core.tar.gz
        - --endpoints
        - constants/emi_english/endpoints_core_tamil.yml
        - --port
        - "8830"
        - -vv
  rasa-core-sriram-tamil1:
    image: "tatisudheer/chatbot"
    volumes:
        - ./models:/app/models
        - ./constants:/app/constants
    ports:
        - "8831:8831"
    network_mode: "host"
    command:
        - -m
        - rasa
        - run
        - --enable-api
        - -m
        - models/emi_english/emi_english_core.tar.gz
        - --endpoints
        - constants/emi_english/endpoints_core_tamil.yml
        - --port
        - "8831"
        - -vv
  # rasa-core-sriram-tamil2:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #       - ./models:/app/models
  #       - ./constants:/app/constants
  #   ports:
  #       - "8832:8832"
  #   network_mode: "host"
  #   command:
  #       - -m
  #       - rasa
  #       - run
  #       - --enable-api
  #       - -m
  #       - models/emi_english/emi_english_core.tar.gz
  #       - --endpoints
  #       - constants/emi_english/endpoints_core_tamil.yml
  #       - --port
  #       - "8832"
  #       - -vv
  # rasa-core-sriram-tamil3:
  #   image: "tatisudheer/chatbot"
  #   volumes:
  #       - ./models:/app/models
  #       - ./constants:/app/constants
  #   ports:
  #       - "8833:8833"
  #   network_mode: "host"
  #   command:
  #       - -m
  #       - rasa
  #       - run
  #       - --enable-api
  #       - -m
  #       - models/emi_english/emi_english_core.tar.gz
  #       - --endpoints
  #       - constants/emi_english/endpoints_core_tamil.yml
  #       - --port
  #       - "8833"
  #       - -vv

  rasa-actions-sriram-tamil:
    image: "tatisudheer/chatbot"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
        - ./models:/app/models
        - ./constants:/app/constants
        - ./actions:/app/actions
        - ./call_logs.csv:/app/call_logs.csv
        - ./customer_details.json:/app/customer_details.json
        - ./customer_details_new.csv:/app/customer_details_new.csv
        - ./handle_bulk_data.py:/app/handle_bulk_data.py
    ports:
        - "5830:5830"
    network_mode: "host"
    command:
        - -m
        - rasa
        - run
        - actions
        - --actions
        - actions.actions
        - --port
        - "5830"
        - -vv
  rasa-actions-sriram-tamil1:
    image: "tatisudheer/chatbot"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
        - ./models:/app/models
        - ./constants:/app/constants
        - ./actions:/app/actions
        - ./call_logs.csv:/app/call_logs.csv
        - ./customer_details.json:/app/customer_details.json
        - ./customer_details_new.csv:/app/customer_details_new.csv
        - ./handle_bulk_data.py:/app/handle_bulk_data.py
    ports:
        - "5831:5831"
    network_mode: "host"
    command:
        - -m
        - rasa
        - run
        - actions
        - --actions
        - actions.actions
        - --port
        - "5831"
        - -vv
  rasa-actions-sriram-tamil2:
    image: "tatisudheer/chatbot"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
        - ./models:/app/models
        - ./constants:/app/constants
        - ./actions:/app/actions
        - ./call_logs.csv:/app/call_logs.csv
        - ./customer_details.json:/app/customer_details.json
        - ./customer_details_new.csv:/app/customer_details_new.csv
        - ./handle_bulk_data.py:/app/handle_bulk_data.py
    ports:
        - "5832:5832"
    network_mode: "host"
    command:
        - -m
        - rasa
        - run
        - actions
        - --actions
        - actions.actions
        - --port
        - "5832"
        - -vv
  rasa-actions-sriram-tamil3:
    image: "tatisudheer/chatbot"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
        - ./models:/app/models
        - ./constants:/app/constants
        - ./actions:/app/actions
        - ./call_logs.csv:/app/call_logs.csv
        - ./customer_details.json:/app/customer_details.json
        - ./customer_details_new.csv:/app/customer_details_new.csv
        - ./handle_bulk_data.py:/app/handle_bulk_data.py
    ports:
        - "5833:5833"
    network_mode: "host"
    command:
        - -m
        - rasa
        - run
        - actions
        - --actions
        - actions.actions
        - --port
        - "5833"
        - -vv
  # rasa-actions-sriram-tamil4:
  #   image: "tatisudheer/chatbot"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   volumes:
  #       - ./models:/app/models
  #       - ./constants:/app/constants
  #       - ./actions:/app/actions
  #       - ./call_logs.csv:/app/call_logs.csv
  #       - ./customer_details.json:/app/customer_details.json
  #       - ./customer_details_new.csv:/app/customer_details_new.csv
  #   ports:
  #       - "5834:5834"
  #   network_mode: "host"
  #   command:
  #       - -m
  #       - rasa
  #       - run
  #       - actions
  #       - --actions
  #       - actions.actions
  #       - --port
  #       - "5834"
  #       - -vv
  # rasa-actions-sriram-tamil5:
  #   image: "tatisudheer/chatbot"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   volumes:
  #       - ./models:/app/models
  #       - ./constants:/app/constants
  #       - ./actions:/app/actions
  #       - ./call_logs.csv:/app/call_logs.csv
  #       - ./customer_details.json:/app/customer_details.json
  #       - ./customer_details_new.csv:/app/customer_details_new.csv
  #   ports:
  #       - "5835:5835"
  #   network_mode: "host"
  #   command:
  #       - -m
  #       - rasa
  #       - run
  #       - actions
  #       - --actions
  #       - actions.actions
  #       - --port
  #       - "5835"
  #       - -vv
  # rasa-actions-sriram-tamil6:
  #   image: "tatisudheer/chatbot"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   volumes:
  #       - ./models:/app/models
  #       - ./constants:/app/constants
  #       - ./actions:/app/actions
  #       - ./call_logs.csv:/app/call_logs.csv
  #       - ./customer_details.json:/app/customer_details.json
  #       - ./customer_details_new.csv:/app/customer_details_new.csv
  #   ports:
  #       - "5836:5836"
  #   network_mode: "host"
  #   command:
  #       - -m
  #       - rasa
  #       - run
  #       - actions
  #       - --actions
  #       - actions.actions
  #       - --port
  #       - "5836"
  #       - -vv

  app_server-sriram-tamil:
    image: "tatisudheer/chatbot"
    volumes:
      - ./nlu:/app/nlu
    ports:
      - "12216:12216"
    network_mode: "host"
    command:
      - nlu/emi_english/app_tamil.py

  nlg_server-sriram-tamil:
    image: "tatisudheer/chatbot"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
    - ./nlg:/app/nlg
    - ./Sheet1.json:/app/Sheet1.json
    ports:
    - "13216:13216"
    network_mode: "host"
    command:
    - nlg/emi_english/nlg_server_tamil.py

  Orchestrator-sriram-tamil:
    image: "tatisudheer/chatbot"
    volumes:
    - ./Orchestrator/CZ:/app/Orchestrator/CZ
    - ./customer_details.json:/app/customer_details.json
    - ./handle_bulk_data.py:/app/handle_bulk_data.py
    ports:
    - "7116:7116"
    network_mode: "host"
    command:
    - Orchestrator/CZ/orchestrator_tamil.py

